/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PisProjekt;

public class App {

    public static void main(String[] args) {
        ZombieShooter.main(new String[0]);
    }
}
